### ISSUE TITLE
Error: Cannot find module '.../histogram.node'

### ISSUE THREAD

**Issue by rolandg** [mcollina/autocannon#108]
I'm getting following error after successful global install on ArchLinux.

```
module.js:487
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/autocannon/node_modules/native-hdr-histogram/lib/binding/node-v57-linux-x64/histogram.node'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/autocannon/node_modules/native-hdr-histogram/histogram.js:6:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by mcollina** [comment]
which version of Node.js are you using?

**Comment by rolandg** [comment]
```
$ node -v
v8.1.3
```

**Comment by mcollina** [comment]
can you reinstall, and upload all the npm output to gist and link it here?

Maybe reinstalling will actually fix it.

**Comment by rolandg** [comment]
For some reason uninstalling and reinstalling fixed the issue. can't reproduce.
