### ISSUE TITLE
Fresh install fails with module not found error

### ISSUE THREAD

**Issue by iest** [mcollina/autocannon#126]
The culprit is `hdr-histogram-js`, I've opened an issue here: https://github.com/HdrHistogram/HdrHistogramJS/issues/8

I'd consider pinning to `v.1.0.0` of `hdr-histogram-js` until the dependancy is fixed.

Error for verbosity:
```
Error: Cannot find module 'hdr-histogram-js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/autocannon/lib/run.js:5:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by mcollina** [comment]
Fixed in v2.1.1.
