### ISSUE TITLE
All responses are non 2xx with method POST in Hapi.js

### ISSUE THREAD

**Issue by nejc001** [mcollina/autocannon#153]
I made same post in hapi/disscuss (https://github.com/hapijs/discuss/issues/705) repository, since this only apeared with Hapi framework. But then i realized that with GET method it works fine, but POST fails.
I added header property in the call and the problem still persists.

![hapierr2](https://user-images.githubusercontent.com/11994606/44297996-3d03d900-a2db-11e8-975e-5417ab49cf3a.PNG)

**Comment by mcollina** [comment]
Have you tried with curl? Does it work?
Can you please add the source code of your test server? Have you checked your Hapi logs?

**Comment by nejc001** [comment]
Tried with Postman and the response works as it should with 200 status.

Hapi server is basic:
![hapi err server](https://user-images.githubusercontent.com/11994606/44298419-1184ec80-a2e3-11e8-87f9-cf0282e09b5a.PNG)

Hapi logs are spammed with:
`{"level":40,"time":1534587852721,"pid":1740,"hostname":"Nejc-PC","err":{"type":"Error","message":"read ECONNRESET","stack":"Error: read ECONNRESET\n    at _errnoException (util.js:1022:11)\n    at TCP.onread (net.js:628:25)","code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"},"v":1}`

Note: I am running server with PM2 and tried same test on other servers like express, koa, loopback, nest, feathers, sails and they worked.

**Comment by mcollina** [comment]
I think It’s a problem with http keep-alive. Considering all other frameworks and node core works with it, I’m leaning towards thinking it’s an Hapi bug or some  configuration (here or in your code).

**Comment by mcollina** [comment]
The following works fine against a simple server defining a POST:

```
autocannon -c 10 -H 'Content-Type: application/json' -m POST -b '{ "hello": "world" }' http://localhost:3000
```

Please provide some example code/project to reproduce this issue.

**Comment by nejc001** [comment]
Project: https://github.com/nejc001/hapi-autocannon-test

![hapi full test error](https://user-images.githubusercontent.com/11994606/44338601-ad972b00-a47e-11e8-90ed-3fa59573bd88.PNG)

Node.js v8.11.1
Autocannon v2.4.1
Hapi v17.5.2

Please confirm if this also happens to you.

**Comment by mcollina** [comment]
Works perfectly here (Mac OS X), can you please try adding the autocannon command as a npm script? From your screenshot it seems the outer `}`  is missing.

If you have access to a Linux VM, can you please confirm if you see the same problem there? Can you also confirm that there are not a) docker container runnning  and b) other Node.js processes running?

Can you please use IP addresses instead? `localhost` on Windows resolves to `::1` first, and then to `127.0.0.1`. I've seen some weird behavior happening because of that.

**Comment by nejc001** [comment]
Command was correct, just hidden on the screen.
No access to Linux VM and have no docker or other Node.js processes running.

On left is Express server generated with express-generator package (port 3000).
On right is this Hapi server (port 3010).
![hapi-express autocannon](https://user-images.githubusercontent.com/11994606/44347244-97499900-a497-11e8-9160-ab6ba6acc41d.PNG)

I will test this on different PC's and report back.

**Comment by nejc001** [comment]
On 2 different laptops with same project, as on images above, on Windows 10 i get the same issue.
Before i was running it on Windows 7.

Here i did a curl call of the server with (with -v and -i) and the same call with autocannon:
![zajeta slika](https://user-images.githubusercontent.com/11994606/44506996-28dc2500-a6a9-11e8-94f0-7f83579a9b75.PNG)

**Comment by mcollina** [comment]
It works smoothly with  

`autocannon -c 10 -H "Content-Type: application/json" -m POST -b "{ \"hello\": \"world\" }'" http://127.0.0.1:3000`

on my Windows machine.

I've submitted #157 which will avoid the messy `'` behavior.

**Comment by guiOLVR** [comment]
i have the same problem, but i used fastify in windows 10.

I try run this: 
`autocannon -c 10 -H "Content-Type: application/json" -m POST -b "{ \"username\": \"test\",\"password\": \"123\" }'" http://127.0.0.1:3000/user/login`

0 2xx responses, 56618 non 2xx responses
57k requests in 11.05s, 28.2 MB read

what is wrong?

**Comment by thekemkid** [comment]
@guiOLVR What version are you running now?

**Comment by guiOLVR** [comment]
autocannon v4.1.1
node v10.15.3
