### ISSUE TITLE
Use in Typescript

### ISSUE THREAD

**Issue by amit12cool** [mcollina/autocannon#221]
How can i import autocannon in Typescript?

Below doesn't work:-

import * as autocannon from 'autocannon'
import autocannon from 'autocannon'
const autocannon = import('autocannon')

**Comment by mcollina** [comment]
I've never used this in Typescript. It would be good to have a PR with typings!

**Comment by amit12cool** [comment]
I got the type definitions here
// Type definitions for autocannon 4.1
// Project: https://github.com/mcollina/autocannon#readme
// Definitions by: Jeremy Bensimon <https://github.com/jeremyben>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.1

Checkout
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/autocannon/autocannon-tests.ts

But still I face issues doing
import autocannon = require('autocannon');

Error is below:-


import autocannon = require('autocannon');
       ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by davidmarkclements** [comment]
that's an incorrect import statement I think

```js
import autocannon from 'autocannon'
```

**Comment by amit12cool** [comment]
Yes, that’s incorrect. But im not sure what is correct then.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by davidmarkclements** [comment]
no.. the correct form is:

import autocannon from 'autocannon'

**Comment by amit12cool** [comment]
The error is below:-

import autocannon from 'autocannon';
       ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by davidmarkclements** [comment]
that error stack suggests you're trying to run typescript directly with
node, you need to use typescript tooling to use typescript.

**Comment by amit12cool** [comment]
Correct. Thanks Just got that working.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
