### ISSUE TITLE
Setting workers to >= 10 yields eventemitter warnings

### ISSUE THREAD

**Issue by jasnell** [mcollina/autocannon#337]
```
root@DESKTOP-5KK9VIR:~/node/node# autocannon -w 10 localhost:3000
Running 10s test @ http://localhost:3000
10 connections
10 workers

⠋ running...(node:9067) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11
 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9067) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error liste
ners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:9067) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close liste
ners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:9067) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish list
eners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
⠦ running...
```

**Comment by brainrepo** [comment]
It seems related to the "ora" package use made by "progressTracker" in the workers' mode.

```
(node:2889) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 23 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:389:17)
    at WriteStream.addListener (events.js:405:10)
    at WriteStream.Readable.on (_stream_readable.js:856:35)
    at WriteStream.once (events.js:436:8)
    at BufferListStream.Readable.pipe (/Users/mauro/Desktop/nearform/autocannon-test/node_modules/readable-stream/lib/_stream_readable.js:723:8)
    at new StdinDiscarder (/Users/mauro/Desktop/nearform/autocannon-test/node_modules/ora/index.js:28:20)
    at new Ora (/Users/mauro/Desktop/nearform/autocannon-test/node_modules/ora/index.js:106:21)
    at oraFactory (/Users/mauro/Desktop/nearform/autocannon-test/node_modules/ora/index.js:390:9)
    at showSpinner (/Users/mauro/Desktop/nearform/autocannon-test/node_modules/autocannon/lib/progressTracker.js:84:15)
    at EventEmitter.<anonymous> (/Users/mauro/Desktop/nearform/autocannon-test/node_modules/autocannon/lib/progressTracker.js:60:9)
```
