### ISSUE TITLE
--forever does not work from the command line

### ISSUE THREAD

**Issue by skywickenden** [mcollina/autocannon#358]
Using the `-f/--forever` flag on the command line results in an error. EG:

```
node autocannon -f http://localhost:5000
```

results in

```
/Users/sky/NearForm/autocannon/autocannon/autocannon.js:235
    initJob(argv).catch((err) => {
                       ^

TypeError: initJob(...).catch is not a function
    at start (/Users/sky/NearForm/autocannon/autocannon/autocannon.js:235:24)
    at Object.<anonymous> (/Users/sky/NearForm/autocannon/autocannon/autocannon.js:264:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by mcollina** [comment]
Good spot! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
