### ISSUE TITLE
RangeError: Invalid typed array length: 0

### ISSUE THREAD

**Issue by ThePrez** [mcollina/autocannon#376]
Running autocannon on the IBM i platform against a handmade application crashes with the following error
```pascal
/QOpenSys/pkgs/lib/nodejs14/lib/node_modules/autocannon/node_modules/@assemblyscript/loader/index.js:241
    return new Type(buffer, bufPtr, U32[bufPtr + SIZE_OFFSET >>> 2] >>> alignLog2);
           ^

RangeError: Invalid typed array length: 0
    at new Uint8Array (<anonymous>)
    at getTypedArrayView (/QOpenSys/pkgs/lib/nodejs14/lib/node_modules/autocannon/node_modules/@assemblyscript/loader/index.js:241:12)
    at getTypedArray (/QOpenSys/pkgs/lib/nodejs14/lib/node_modules/autocannon/node_modules/@assemblyscript/loader/index.js:233:21)
    at WasmHistogram.encode (/QOpenSys/pkgs/lib/nodejs14/lib/node_modules/autocannon/node_modules/hdr-histogram-js/dist/wasm/index.js:204:28)
    at WasmHistogram.encodeWasmIntoCompressedBase64 [as encodeIntoCompressedBase64] (/QOpenSys/pkgs/lib/nodejs14/lib/node_modules/autocannon/node_modules/hdr-histogram-js/dist/encoding.js:46:35)
    at Object.exports.encodeIntoCompressedBase64 (/QOpenSys/pkgs/lib/nodejs14/lib/node_modules/autocannon/node_modules/hdr-histogram-js/dist/encoding.js:55:26)
    at encodeHist (/QOpenSys/pkgs/lib/nodejs14/lib/node_modules/autocannon/lib/histUtil.js:40:14)
    at Timeout.tickInterval (/QOpenSys/pkgs/lib/nodejs14/lib/node_modules/autocannon/lib/run.js:111:20)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7)
```
Node.js version is 14.16.1
With assemblyscript at the top of the stack, this issue may be misplaced (apologies if so). Also, IBM i Web Assembly support is very limited, so the root cause may very well be in the Node.js build on IBM i.

**Comment by mcollina** [comment]
Unfortunately autocannon uses webassembly internally, so t mge IBM i platform is not supported.
