### ISSUE TITLE
Cannot Use on OpenWhisk Actions Using Webpack

### ISSUE THREAD

**Issue by klcodanr** [mcollina/autocannon#432]
I was trying to use autocannon in an OpenWhisk action created with webpack. It seems like when webpack packages up autocannon it doesn't include the dynamic call to read help.txt thus autocannon fails when invoked with:

    Initialization has failed due to: Error: ENOENT: no such file or directory, open '/nodejsAction/G7zjExia/help.txt'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.52430 (/nodejsAction/G7zjExia/index.js:79610:17)
    at __webpack_require__ (/nodejsAction/G7zjExia/index.js:186808:42)
    at Object.78163 (/nodejsAction/G7zjExia/index.js:24:20)
    at __webpack_require__ (/nodejsAction/G7zjExia/index.js:186808:42)
    at /nodejsAction/G7zjExia/index.js:186875:37
    at Object.<anonymous> (/nodejsAction/G7zjExia/index.js:186878:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

My thought would be to _either_ wrap the read of help.txt in a try-catch or convert the help.txt into a JSON that can be included with require and thus be found by webpack when it shakes the tree.

**Comment by mcollina** [comment]
You can configure webpack to bundle static files or to emit the needed static files in the right places. I do not have a quick how to but this was done in the past.

I don't think we should modify autocannon to support this.

**Comment by klcodanr** [comment]
I may be missing it in webpack's documentation, but I don't see how I can do this for a dependency of my module. 

Either way it seems unintuitive / unfriendly for autocannon to fail at runtime when it's used in a library built with a common build tool like webpack. 

If the concern is on impacting autocannon, would a reasonable solution be to instead wrap the read of the help.txt in a try-catch? When using autocannon as a dependency, I wouldn't expect the help to relevant anyway.

**Comment by mcollina** [comment]
> If the concern is on impacting autocannon, would a reasonable solution be to instead wrap the read of the help.txt in a try-catch? When using autocannon as a dependency, I wouldn't expect the help to relevant anyway.

A better option is to split https://github.com/mcollina/autocannon/blob/master/autocannon.js into two files:

1. the entrypoint for the module
2. the entrypoint for the CLI

Would you do that? Thanks

**Comment by klcodanr** [comment]
Sure. I'll close the PR on the previous approach.

**Comment by klcodanr** [comment]
@mcollina well it turns out that fix is _really_ easy, just move the call to read the help inside of the `parseArguments` function.
