### ISSUE TITLE
Cannot make setupRequest function async

### ISSUE THREAD

**Issue by rohitbaisane** [mcollina/autocannon#489]
I am getting error when making setupRequest async function ,
       
code : -                       
 setupRequest: async (req, context) => {
        console.log(req);
        const data = await InputGenerator();
        req.body = JSON.parse(data);
        req.path = '/thisispath'
        return req;
      }
error: - 
/home/appgambit016/Desktop/Tools/MonitoringServer/node_modules/autocannon/lib/util.js:7
  for (const objKey of Object.keys(obj)) {
                              ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getPropertyCaseInsensitive (/home/appgambit016/Desktop/Tools/MonitoringServer/node_modules/autocannon/lib/util.js:7:31)
    at RequestIterator.buildRequest [as requestBuilder] (/home/appgambit016/Desktop/Tools/MonitoringServer/node_modules/autocannon/lib/httpRequestBuilder.js:48:16)
    at RequestIterator.rebuildRequest (/home/appgambit016/Desktop/Tools/MonitoringServer/node_modules/autocannon/lib/requestIterator.js:108:17)
    at /home/appgambit016/Desktop/Tools/MonitoringServer/node_modules/autocannon/lib/requestIterator.js:74:12
    at Array.forEach (<anonymous>)
    at RequestIterator.setRequests (/home/appgambit016/Desktop/Tools/MonitoringServer/node_modules/autocannon/lib/requestIterator.js:71:17)
    at new RequestIterator (/home/appgambit016/Desktop/Tools/MonitoringServer/node_modules/autocannon/lib/requestIterator.js:35:8)
    at new Client (/home/appgambit016/Desktop/Tools/MonitoringServer/node_modules/autocannon/lib/httpClient.js:36:26)
    at initialiseClients (/home/appgambit016/Desktop/Tools/MonitoringServer/node_modules/autocannon/lib/run.js:210:22)

**Comment by mcollina** [comment]
This is expected, the function is supposed to be synchronous.
