### ISSUE TITLE
broken progress

### ISSUE THREAD

**Issue by alexindigo** [mcollina/autocannon#52]
I installed autocannon as local module (it had some issues with global installation),
and getting js error while trying to run simple test:

```
$ autocannon -c 1 -d 1s http://n...
/home/alexi/autocannon/node_modules/autocannon/node_modules/progress/lib/node-progress.js:51
    if ('number' != typeof options.total) throw new Error('total required');
                                          ^

Error: total required
    at new ProgressBar (/home/alexi/autocannon/node_modules/autocannon/node_modules/progress/lib/node-progress.js:51:49)
    at track (/home/alexi/autocannon/node_modules/autocannon/lib/progressTracker.js:28:25)
    at start (/home/alexi/autocannon/node_modules/autocannon/autocannon.js:92:5)
    at Object.<anonymous> (/home/alexi/autocannon/node_modules/autocannon/autocannon.js:101:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```

Thank you.

PS. Linux, node@4.4.7, npm@2.15.8

**Comment by thekemkid** [comment]
have you tried `autocannon -c 1 -d 1 http://n...`?

**Comment by alexindigo** [comment]
Ha, API was too close to wrk but not the same :) And thanks for the quick fix.

**Comment by thekemkid** [comment]
Your original command should work now, now 👍 Happy to help
